### ISSUE TITLE
Peer Review Feedback

### ISSUE THREAD

**Issue by nicc00** [macebal1/Project-Repository#2]
Technical-
Make the email link clickable
Dropdown menu on recipes page to select each one individually instead of having to scroll through the whole page
Content- 
Images of workout maybe to fill the page and make it more appealing
Maybe suggest some other fitness sites that you like or are helpful

**Comment by macebal1** [comment]
Completely forgot about the email link, so thank you for the reminder! Great suggestions will definitely take these into account :)
